inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/CommentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SymbolArray:
  Enabled: false
