inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SymbolArray:
  Enabled: false
