version: '3.3'

services:
  db:
    image: postgres:9.6 # Required version to run tests with Rails 4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-planner}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-planner}

  web:
    volumes:
      - .:/srv/app

  delayed-job:
    volumes:
      - .:/srv/app
