services:
  db:
    volumes:
      - ./app:/srv/app/app

  web:
    volumes:
      - .:/srv/app
    ports:
      - 127.0.0.1:8180:8080

  delayed-job:
    volumes:
      - .:/srv/app
    deploy:
      replicas: 1
