services:
  superset:
    image: superset:3.1.3
    build:
      context: ../docker/superset
    depends_on:
      - db
      - superset_redis
    entrypoint: ["/app/pythonpath/entrypoint.sh"]
    environment:
      SUPERSET_SECRET_KEY: lkfzoiezhfoizehfoizhoihfopizajfoizafjpoizaufepoaz
      DATABASE_DIALECT: postgresql+psycopg2
      POSTGRES_DB: ${POSTGRES_DB:-planner}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-planner}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-planner}
      REDIS_HOST: superset_redis
      SUPERSET_DB: superset
      SUPERSET_ADMIN_USERNAME: admin
      SUPERSET_ADMIN_EMAIL: admin@superset.com
      SUPERSET_ADMIN_PASSWORD: admin
      MAPBOX_API_KEY: ${SUPERSET_MAPBOX_API_KEY}
    volumes:
      - ../docker/superset:/app/pythonpath
    ports:
      - 127.0.0.1:8088:8088
    restart: unless-stopped
    networks:
      - public-network

  superset_redis:
    image: redis:${REDIS_VERSION:-7-alpine}
    restart: unless-stopped
    networks:
      - public-network

  superset_nginx:
    image: superset_nginx
    build:
      context: ../docker/superset_nginx
    depends_on:
      - web
      - superset
    restart: unless-stopped
    networks:
      - public-network

networks:
  public-network:
    name: public-network
    external: true
