x-web: &web
  build:
    context: ..
    dockerfile: .devcontainer/Dockerfile
  image: ghcr.io/cartoway/planner-web:${CARTOWAY_VERSION:-dev}
  environment:
    RAILS_ENV: ${RAILS_ENV:-production}
    NODE_ENV: ${NODE_ENV:-production}
    GEOCODER_URL: ${GEOCODER_URL:-http://localhost:8081/0.1}
    GEOCODER_API_KEY: ${GEOCODER_API_KEY:-demo}
    ROUTER_URL: ${ROUTER_URL:-http://localhost:8082/0.1}
    ROUTER_API_KEY: ${ROUTER_API_KEY:-demo}
    OPTIMIZER_URL: ${OPTIMIZER_URL:-http://localhost:8083/0.1}
    OPTIMIZER_API_KEY: ${OPTIMIZER_API_KEY:-demo}
    SENTRY_DSN: ${SENTRY_DSN}
    HERE_MAP_APIKEY: ${HERE_MAP_APIKEY}
    LOG_FORMAT: ${LOG_FORMAT}
    URL_SHORTENER: ${URL_SHORTENER:-http://url_shortener:8635}
    AVAILABLE_SOLVERS: ${AVAILABLE_SOLVERS:-}
    POSTGRES_USER: ${POSTGRES_USER:-planner}
    POSTGRES_DB: ${POSTGRES_DB:-planner}
    POSTGRES_DB_TEST: ${POSTGRES_DB_TEST:-planner-test}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-planner}
    AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
    AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
    AZURE_TENANT_ID: ${AZURE_TENANT_ID}
  volumes:
    - ../config/database.yml.docker:/srv/app/config/database.yml
    - ../.devcontainer/production.rb:/srv/app/config/environments/production.rb
    - ../docker/uploads:/srv/app/public/uploads
  depends_on:
    db:
      condition: service_healthy
    redis-cache:
      condition: service_started
  restart: unless-stopped

services:
  db:
    # Place a dump file in the docker/dumps directory to load the database from it if no database is found
    # Devcontainer might display that the container is not running, but the database might be loading the dump
    # Or the web container might be running the migrations. Wait until the database is ready.
    image: postgis/postgis:15-3.5

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${POSTGRES_USER:-planner}
      - POSTGRES_DB=${POSTGRES_DB:-planner}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-planner}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../docker/dumps:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-planner} -d ${POSTGRES_DB:-planner} && psql -U ${POSTGRES_USER:-planner} -d ${POSTGRES_DB:-planner} -c '\\dt' | grep -q public"]
      start_interval: 5s
      start_period: 60s
      interval: 60s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - public-network

  redis-cache:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save ""
    networks:
      - public-network

  web:
    <<: *web
    command: bash -c "LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 bundle exec rake db:prepare && bundle exec puma -v -p 8080 --pidfile 'server.pid' -t ${PUMA_WORKERS:-0:1}"
    networks:
      - public-network

  delayed-job:
    <<: *web
    command: bash -c "bundle exec rails runner 'Delayed::Job.delete_all' && LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 bundle exec './bin/delayed_job run'"
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      web:
        condition: service_started
    deploy:
      replicas: ${DELAYED_JOB_REPLICAS:-1}
    networks:
      - public-network

volumes:
  pg_data:

networks:
  public-network:
    name: public-network
    attachable: true
