http:
  routers:
    web:
      service: web
      entrypoints: web
      rule: HostRegexp(`.*`)
      middlewares:
        - retry

    url_shortener:
      service: url_shortener
      entrypoints: url_shortener
      rule: HostRegexp(`.*`)
      middlewares:
        - retry

  serversTransports:
    web_transport:
      forwardingTimeouts:
        dialTimeout: 30s # equivalent to ngnix proxy_connect_timeout
        responseHeaderTimeout: 1000s # equivalent to ngnix proxy_read_timeout
        idleConnTimeout: 1000s # roughly aligned with ngnix send_timeout

  services:
    web:
      loadbalancer:
        servers:
          - url: http://web:8080
        serversTransport: web_transport
        healthcheck:
          path: /
        sticky:
          cookie:
            secure: true
            httpOnly: true
            samesite: none

    url_shortener:
      loadbalancer:
        servers:
          - url: http://url_shortener:8635
        healthcheck:
          path: /

  middlewares:
    retry:
      retry:
        attempts: 5
        initialinterval: 1000ms
